### PR TITLE
Docker CI

### LINKED ISSUE #91: Add Docker CI
Docker image building and pushing to ghcr support would be amazing.

### PR DESCRIPTION
**Pull request by kubo6472**
Closes #91

### CODE REVIEW

**Comment by kubo6472** [comment]
I managed to build a container. Calling it a day. Seems like the env vars are not properly translated AND it does not use the Nix stuff.

**Comment by kubo6472** [comment]
What works works, but it is terribly inefficient and takes hours, so not really ready for a merge just yet, but I am playing with the Nix builds now and it goes somewhere. I realized I had something yesterday, too, I just did not read the docs good enough 😅

**Comment by girlbossceo** [comment]
> What works works, but it is terribly inefficient and takes hours

This may be because of my max build-time optimisations and rather not something you're doing. When I merge https://github.com/girlbossceo/conduwuit/pull/87 please try again.

**Comment by kubo6472** [comment]
Closing in favor of #97

**Pull request closed without merging**
