### PR TITLE
disable overflow-checks for performance

### PR DESCRIPTION
**Pull request by girlbossceo**

### CODE REVIEW

**Comment by Xiretza** [comment]
What is the benchmarked performance gain from this? Is it really worth throwing away the correctness checks?

**Comment by jevolk** [comment]
Arithmetic overflow in Rust is not permitted by static analyses and idiomatic practices including rich API's for saturation, wrapping, and checked operations expressing an explicit intent that ought to be enforced by proper build tools. Thus there is no reason for arithmetic incorrectness at runtime any more than there is for memory incorrectness.

These overflow-checks are a runtime feature which generate a conditional branch after every arithmetic operation. This is a feature inherited from the compiler infrastructure Rust was built on, and is offered to the front-end as an option. It is an option. It is not required for correctness. It is thus not enabled by default, but still has value within debug and test mode builds, similar to `debug_assert!`, but it is not for production code. I would strongly encourage its use during unit and integration tests.

There are a few problems with overflow-checks in production code. At the compiler level there are _many_ inhibitions to optimization. These inhibitions are only growing in their severity as the need for ILP to make up for the plateau in single-core performance for the last twenty years is absolutely paramount right now and going forward.

At the hardware level, the branch predictor has a finite amount of memory for each segment of instructions and the **branch density** from overflow checks is basically guaranteed to exceed that. This will come at the cost of evicting predictions from normal control flow in the actual application logic. Lastly, the increased code size from the conditions consumes L1i at the expense of other cache which could have also held application logic.

Overflow checks have been a vigorously researched topic both academically and within Rust's design community, either of whom provide proper benchmarks with some scientific rigor. I encourage you to look into those and return here if you believe it's worth contriving benchmarks specific to this application which would counter the strongly expected hypothetical.

**Comment by Benjamin-L** [comment]
We do not have compile-time guarantees against arithmetic overflow in rust in the same that we have guarantees against UB from memory unsafety. It is possible to write rust code that is reasonably protected from overflow by using the saturating/checked arithmetic methods, but conduwuit is not doing this currently. If we wanted to go that route, we would probably want to start by enabling the [`integer_arithmetic`](https://rust-lang.github.io/rust-clippy/v0.0.212/index.html#integer_arithmetic) clippy lint. This lint generates 125 warnings against the current codebase, so we have a long way to go. It's also worth noting that the `integer_arithmetic` lint will not protect us from integer overflow bugs in our dependencies.

My vote is generally that we should default to preferring correctness over performance for a security-sensitive networked application.

**Comment by girlbossceo** [comment]
Realistically I'd prefer if we can deal with the *majority* (not all) of cases at the lint level, also including dealing with `as_conversions`. I have no issues working through those lints.

Edgecases will happen but there's an accepted level of risk we should accept. Sure we can start enabling all kinds of LLVM sanitisers or add extra hardening compiler flags to lessen that or whatever, but I think there just needs to be an accepted level of risk here. I do support the security-focused group which is why I spent time and effort getting hardened_malloc-rs working with conduwuit, and obviously why I'm all for lints and ideally the `pedantic` clippy lint in the future, but I can't force that upon everyone and the security/correctness group will be doing more than just enable overflow checks and using hardened_malloc-rs.

**Comment by Xiretza** [comment]
> there just needs to be an accepted level of risk here

An accepted level of safety-performance tradeoff, sure. That's why I had initially asked what the performance impact of this is; only based on that can you make a decision whether overflow checks are worth it or not.

**Comment by jevolk** [comment]
Just to clarify, this is a tool which has existed in compilers long before Rust as one of the earliest forms of _instrumentation_. It exists in the same category as other instrumentation like asan/ubsan as invasive code-modifying instrumentation. This property has even made its use contentious when weighed against other forms of emulation based instrumentation such as valgrind which is non-modifying. It is _instrumentation_ useful to detect errors during debug phases such as with a fuzz-tester.

We could run production software with other instrumentation as a matter of valuing safety over performance. We could also just run it in emulator. I don't see those options being tendered here even though they are just as true to the concept as this one. This is perhaps among hundreds of instruments featured by LLVM which could be enabled but I don't see any objection to not doing so argued here. This is only being raised because it's one which has been documented within cargo's rustc codegen features; it's also documented to not be enabled by default except as a tool alongside debug assertions. Said documentation could provide warnings and handwringing about disabling, but it does not because it's understood to be instrumentation. These are conscious decisions.

So the conclusion is that static analyses and idiomatic practices are the correct way to approach arithmetic correctness, similar to other domains of correctness. Thanks @Benjamin-L for pointing out the availability of this lint. I think it should be enabled and these problems fixed the way they ought to be: before they become problems in the first place. I'm slightly disappointed these aren't enabled by default and treated more seriously by the toolchain. I'm not sure why this isn't considered a bug in the toolchain's default configuration.

**Pull request merged**
